name: Push Phrase
on:
  push:
    branches: ["main", "feat/phrase"]
    paths:
      - messages/en-US.json
jobs:
  deploy-phrase:
    if: github.repository == 'inkonchain/ink-web-app'
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: "Install Phrase CLI"
        run: brew install phrase-cli
        env:
          HOMEBREW_NO_INSTALL_CLEANUP: "true"
      - name: "Push Command"
        run: phrase push --access_token $PHRASEAPP_ACCESS_TOKEN --config ./scripts/phrase/.phrase.yml
        env:
          PHRASEAPP_ACCESS_TOKEN: ${{ secrets.PHRASEAPP_ACCESS_TOKEN }}
